version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - db
    volumes:
      - ./airtime/logs:/app/logs
    env_file:
      - .env
    environment:
      DB_NAME: db
      DB_PORT: 5432
    command: >
      /bin/bash -c "
      while !</dev/tcp/db/5432; do
        echo 'Waiting for PostgreSQL...'
        sleep 1
      done;
      echo 'PostgreSQL is up and running';
      exec /app/main
      "
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
